baseURL = "https://rhombus-labs.com"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"
languageCode = "en-us"

title = "Rhombus Labs"
pygmentsCodefences  = true
pygmentsUseClasses  = true
disableKinds = ['RSS']

copyright = "Rhombus Labs"
enableEmoji = true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  themeColor = "#494f5c"
  homeSubtitle = "Coming soon..."
  footerCopyright = "Made with ❤️ in Ukraine"
  gitUrl = "https://github.com/rhombus-labs-hq"
  justifyContent = false
  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/rhombus-labs-hq"

